name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-build:
    name: CI Build
    uses: ./.github/workflows/test.yml
    with:
      BRANCH: ${{ github.event.inputs.BRANCH || github.ref }}
      PROJECT: 'devops'
