name: Test

on:
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string
      PROJECT:
        required: true
        type: string

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: srinivasarao2468/github-actions
          ref: ${{ inputs.BRANCH }}

      # Add your test steps here
      # For example, run unit tests or integration tests
